command_timeout = 500

[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[➜](bold red)"

[cmd_duration]
disabled = true

[directory]
style = "bold italic blue"
read_only = " "

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "

[git_status]
format = ''

[golang]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = ""
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'
