#! /bin/sh

# Start applications from ~/.local/bin/autostart
~/.local/bin/autostart &

# bspwm settings
bspc monitor LVDS-1 -d 1 2 3 4 5 6 7 8 &
bspc config window_gap 8
bspc config border_width 1
bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#fe8019"

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc rule -a Emacs state=tiled
