#+title: Modules used in XMonad polybar
#+property: header-args :tangle modules.ini

* XMonad Workspace
 Before I was using xmonad-log package to have workspace name shown in polybar but, as it was complex and had a lot of code so instead I found a new method, just use EwmhDesktops package builtin XMonad and done.
 #+begin_src conf
[module/xmonad]
type = internal/xworkspaces
pin-workspaces = false
enable-click = false
enable-scroll = false
format = <label-state>

icon-0 = 1;1
icon-1 = 2;2
icon-2 = 3;3
icon-3 = 4;4
icon-4 = 5;5
icon-5 = 6;6
icon-6 = 7;7
icon-7 = 8;8
icon-default = 

label-active = %icon%
label-active-foreground = #ffffff
label-active-padding = 1
label-active-background = #3f3f3f
label-active-underline = #fba922

label-occupied = %icon%
label-occupied-background = ${colors.background}
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 1

label-empty = ""
label-empty-background = ${colors.background}
label-empty-foreground = ${colors.foreground}
 #+end_src

* Power Menu
This is the little button at the top right corner which when clicked open rofi and has multiple options to select, by the way it uses dmenu-scripts to do so just done with the help of rofi.
#+begin_src conf
[module/session]
type = custom/text

click-left = ~/.config/suckless/dmenu/scripts/dm-logout
content = %{T4}%{T- }
content-background = ${colors.lightbg2}
content-foreground = ${colors.foreground}
content-padding = 1
#+end_src

* CPU Usage
As the name suggests this shows how much cpu is being used.
#+begin_src conf
[module/cpu]
type = internal/cpu
interval = 1
format-foreground = ${colors.darkyellow}
format-background = ${colors.lightbg2}
format-prefix = "%{T2}%{T- }"
format-prefix-padding = 1
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.yellow}

label-font = 3
format = <label>
format-padding = 0
label = %{T1} %percentage:1%% %{T-}
#+end_src

* Date
This module shows the current time by default but when clicked it shows date, month, day etc.
#+begin_src conf
[module/date]
type = internal/date
interval = 5
date = " %Y-%m-%d%"
date-alt = " %d-%m-%Y"
time= %H:%M
time-alt = %a %b %d - %I:%M%p
format-prefix = "%{T2}%{T- }"
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.blue}
format-foreground = ${colors.blue}
format-background = ${colors.lightbg2}
format-padding = 0
format-prefix-padding = 1
label =%{T1} %time% %{T-}
#+end_src

* RAM Usage
This module how much ram is in use in MB, if you want you can make it to show it in GB also just use `gb_used` instead of `mb_used`.
#+begin_src conf
[module/memory]
type = internal/memory
interval = 1
label = %{T1} %mb_used% %{T-}
format = <label>
format-prefix = "%{T2}%{T- }"
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.aqua}
format-foreground = ${colors.aqua}
format-background = ${colors.lightbg2}
format-padding = 0
format-prefix-padding = 1
#+end_src

* Volume
This module uses pulseaudio to show volume percentage, though I currently don't use it but in case of emergency.
#+begin_src conf
[module/volume]
type = internal/pulseaudio
label-volume = %{T1} %percentage%% %{T- }
label-muted = %{T1} muted %{T- }
format-volume = <label-volume>
format-volume-prefix = "%{T2}%{T- }"
format-muted-prefix = "%{T2}%{T- }"
format-volume-prefix-padding = 1
format-muted-prefix-padding = 1
format-volume-prefix-foreground = ${colors.darkbg}
format-volume-prefix-background = ${colors.darkgreen}
format-volume-foreground = ${colors.darkgreen}
format-volume-background = ${colors.lightbg2}
format-muted-prefix-foreground = ${colors.darkbg}
format-muted-prefix-background = ${colors.darkgreen}
format-muted-foreground = ${colors.darkgreen}
format-muted-background = ${colors.lightbg2}
#+end_src

* Custom Seprator
Yes you can have it.
#+begin_src conf
[module/sep]
type = custom/text
content = -
content-padding = 1
content-foreground = ${colors.foreground}
content-background =  ${colors.background}
format-foreground = ${colors.foreground}
format-background = ${colors.background}
#+end_src

* Uptime
Shows how long your computer has been cooking.
#+begin_src conf
[module/uptime]
type = custom/script
exec = uptime -p | sed 's/up //' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/'
interval = 100
label =  %{T1} %output% %{T-}
format = <label>

format-prefix = "%{T5}%{T-}"
format-prefix-padding = 1
format-background = ${colors.lightbg2}
format-foreground = ${colors.green}
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.darkgreen}
#+end_src

* Music
Uses `mpd` script in `.local/bin/` to show title of currently playing song.
#+begin_src conf
[module/music]
type = custom/script
interval = 1
format = <label>
format-prefix = "%{T2}%{T- }"
format-prefix-padding = 1
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.purple}
format-foreground = ${colors.darkpurple}
format-background = ${colors.lightbg2}
exec = bash ~/.local/bin/mpd
tail = true
label= %{T1} %output% %{T-}
#+end_src

* Battery
This took the most time.
#+begin_src conf
[module/battery]
type = internal/battery
full-at = 100
low-at = 20
battery = BAT0
adapter = ADP1
poll-interval = 5

format-charging-prefix = "%{T4}%{T- }"
format-discharging-prefix = "%{T4}%{T- }"
format-full-prefix = "%{T4}%{T- }"
format-charging-prefix-padding = 1
format-full-prefix-padding = 1
format-discharging-prefix-padding = 1

format-charging = <label-charging>
format-discharging = <label-discharging>
format-full = <label-full>

format-full-prefix-foreground = ${colors.darkbg}
format-full-prefix-background = ${colors.orange}
format-full-foreground = ${colors.orange}
format-full-background = ${colors.lightbg2}

format-charging-prefix-foreground = ${colors.darkbg}
format-charging-prefix-background = ${colors.orange}
format-charging-foreground = ${colors.orange}
format-charging-background = ${colors.lightbg2}

format-discharging-prefix-foreground = ${colors.darkbg}
format-discharging-prefix-background = ${colors.orange}
format-discharging-foreground = ${colors.orange}
format-discharging-background = ${colors.lightbg2}

label-charging =  %{T1} %percentage%%(+) %{T- }
label-discharging = %{T1} %percentage%%(-) %{T- }
label-full = %{T1} %percentage%%(o) %{T- }
label-low = BATTERY LOW
#+end_src

* Keyboard Indicator
Show the varint of keyboard in use.
#+begin_src conf
[module/keyboard]
type = internal/xkeyboard
blacklist-0 = num lock
blacklist-1 = scroll lock
format = <label-layout>
format-prefix = "%{T2}%{T- }"
format-prefix-padding = 1
label-layout = %variant%
label-layout-padding = 1
format-prefix-foreground = ${colors.darkbg}
format-prefix-background = ${colors.red}
label-layout-background = ${colors.lightbg2}
label-layout-foreground = ${colors.red}
#+end_src
